services:
  - type: web
    name: la-pizzeria-da-claudio
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
